### ISSUE TITLE
Swift Package Dependencies

### ISSUE THREAD

**Issue by RobertSasak** [friyiajr/RealtimeWatchApp#2]
Thank you for a great tutorial. 

I wonder if you perhaps know how to also add Swift Package Dependencies into Expo project? 
Especially I need https://swiftpackageregistry.com/dmytro-anokhin/url-image

**Comment by friyiajr** [comment]
Hey, unfortunately I don't know how to do that. I recommend asking in the Expo Discord - https://discord.com/invite/expo
